apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    author: dhiraj
    type: db
spec:
  containers:
    - name: MYDB
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: admin
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_DB
          value: mydd
          